export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const COMPANY_REGISTER_SUCCESS = "COMPANY_REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const AUTH_START = "AUTH_START";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED = "USER_LOADED";
export const LOGOUT = "LOGOUT";
